size_filter: false
config_threshold: 50
correct_for_lighting: false

compressed_dir: ./compressed_videos
reference_path: ./data/reference.jpg

# Model configuration
inhouse_model: true
# If using a custom model, set inhouse_model to true and provide the path to the model
model_path: ./app/model.pt
model_project_name: tomato-ripness-unripness
model_api_url: https://outline.roboflow.com # https://serverless.roboflow.com
model_version: 1

video_list:
  - tomato_1.mov
  - tomato_2.mp4
experimentation:
  tomato_1.mov:
    foreground_fruit_size: 20000
    background_fruit_size: 1000
    video_resolution: [864, 486]
  tomato_2.mp4:
    foreground_fruit_size: 20000
    background_fruit_size: 3000
    video_resolution: [864, 486]
