size_filter: true
config_threshold: 20
correct_for_lighting: true

reference_image: reference.jpg
video_path: shielded_screen.mp4
model_path: model.pt

selected_scenario: day_light
experimentation:
  day_light: 
    foreground_fruit_size: 50000
    background_fruit_size: 7000
  pink_light:
    foreground_fruit_size: 30000
    background_fruit_size: 3500
  shielded_screen:
    foreground_fruit_size: 50000
    background_fruit_size: 7000